### ISSUE TITLE
Issue with loading checkpointed model for inference

### ISSUE THREAD

**Issue by jtwang1027** [graphcore/ogb-lsc-pcqm4mv2#8]
Hi, thanks for the great work. I'm running into an issue with model inference in the `notebook_inference.ipynb` using the `GPS_4layer` model  on the preprocessed_dataset containing the single smiles example.  When I get to the `predict` step and this is called: `model.load_weights(checkpoint_path).expect_partial()`, I run into this dtype error

```
   prediction, _ = predict(graph_preprocessed, checkpoint_path, "test-challenge", cfg)
  File "/gps/notebook_utils.py", line 94, in predict
    model.load_weights(checkpoint_path).expect_partial()
  File "/venv/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/venv/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 1601, in convert_to_tensor
    raise ValueError(
ValueError: initial_value: Tensor conversion requested dtype float32 for Tensor with dtype float16: <tf.Tensor: shape=(128,), dtype=float16, numpy=
array([-1.3840e-04, -4.1544e-05, -1.2875e-04, -2.5809e-05,  1.0341e-04,
        3.8207e-05, -3.2365e-05, -4.6790e-05,  7.3314e-06,  9.1600e-04,
       -1.1688e-04,  7.0155e-05,   ... ], dtype=float16)>
```

I think this is leading to downstream inability to load the weights. For example, after this Value Error a bunch of these warnings come up:

```
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer's state 'm' for (root).layer_with_weights-0.node_model.Dense_layers.1.bias
...
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer's state 'm' for (root).layer_with_weights-0.node_model.Norm_layers.0.gamma
...
WARNING:tensorflow:Value in checkpoint could not be found in the restored object: (root).optimizer's state 'm' for (root).layer_with_weights-5.transformer_module.q.kernel
```

Do you have any suggestions here?

Thank you

**Comment by adamjsanders277** [comment]
Hi, thank you for your message.

I have taken a quick look and I am unable to reproduce what you are seeing. There are a few pieces of information that could help me, are you running the notebook on Paperspace? If not, do you know which Poplar SDK are you using? the latest SDK is 3.2.0.

**Comment by jtwang1027** [comment]
Is there any way to run this on a GPU not on Paperspace?

Thank you

**Comment by adamjsanders277** [comment]
The application was developed with Graphcore IPUs in mind so it would take a few changes to run this on GPUs. It's simple to run on IPUs however using the `Run on Gradient` link in the Readme (https://ipu.dev/3CGjC5E). This will setup the correct environment and hardware support for you.
Does that work for you?

**Comment by jtwang1027** [comment]
I'm primarily interested in running on a GPU. I haven't tried the paperspace setup/environment.

It looks like getting this to run on a GPU would require some changes, so I'll close the issue here. Thanks for the quick responses
